/**
 * Runtime-validated contracts — T0-02 (F-01), SPEC section 5.
 *
 * SPEC 5 opens with a `[REQUIREMENT]`: every schema in that section is
 * normative, is implemented here as a runtime-validated type, and is validated
 * at every component boundary — not only at the model boundary. Each export
 * below cites the subsection it implements.
 */

import { z } from "zod";

import {
  MAX_ACTIONS,
  MAX_CLARIFY_CANDIDATES,
  MAX_INDEX,
  MIN_CLARIFY_CANDIDATES,
} from "./constants";

// ---------------------------------------------------------------------------
// Shared primitives
// ---------------------------------------------------------------------------

/**
 * SPEC 5.1 (`id`) and SPEC 7.6.1 rule 2. Element ids are generated by the
 * extension, never by the model, and are the only way an action names a target.
 */
export const ELEMENT_ID_PATTERN = /^el_\d{1,3}$/;

/** SPEC 5.1: `x` and `y` are document-relative, normalized to 0..1 (SPEC 12.6). */
const NormalizedCoordSchema = z.number().min(0).max(1);

/** SPEC 5.1: `role`, `tag`, and `inputType` are lowercase. */
const LowercaseNonEmptySchema = z
  .string()
  .min(1)
  .refine((s) => s === s.toLowerCase(), "must be lowercase");

/** SPEC 5.1: accessible names are truncated to 80 chars by the index builder. */
export const ELEMENT_NAME_MAX_CHARS = 80;

/** SPEC 5.1: element values are truncated to 40 chars. */
export const ELEMENT_VALUE_MAX_CHARS = 40;

/** SPEC 5.2: `document.title`, truncated to 120 chars. */
export const PAGE_TITLE_MAX_CHARS = 120;

/** SPEC 5.3: the normalized transcript handed to the resolver, max 200 chars. */
export const TRANSCRIPT_MAX_CHARS = 200;

/** SPEC 5.9: a spoken clarifying question, max 90 chars. */
export const CLARIFY_QUESTION_MAX_CHARS = 90;

/** SPEC 5.12: a stored page summary, max 1200 chars. */
export const SUMMARY_MAX_CHARS = 1200;

/** SPEC 5.14: the transcript copied into a telemetry record, max 120 chars. */
export const TELEMETRY_TRANSCRIPT_MAX_CHARS = 120;

// ---------------------------------------------------------------------------
// 5.1 ElementIndexEntry
// ---------------------------------------------------------------------------

/** SPEC 5.1. `name` and `value` are page-controlled and must pass through `sanitizeForPrompt()` (8.4) before any prompt. */
export const ElementIndexEntrySchema = z.object({
  /** "el_0".."el_N", assigned in index order, stable for one index build. */
  id: z.string().regex(ELEMENT_ID_PATTERN),
  /** ARIA role, explicit or implicit, lowercase (SPEC 12.3). */
  role: LowercaseNonEmptySchema,
  /** Accessible name, trimmed, newlines collapsed, truncated to 80 chars. */
  name: z.string().max(ELEMENT_NAME_MAX_CHARS),
  /** Normalized name used for matching (SPEC 7.2.1). */
  nameKey: z.string(),
  /** Document-relative horizontal centre, 0..1 (SPEC 12.6). */
  x: NormalizedCoordSchema,
  /** Document-relative vertical centre, 0..1 (SPEC 12.6). */
  y: NormalizedCoordSchema,
  /** False if disabled, aria-disabled="true", or readonly. */
  enabled: z.boolean(),
  /** SPEC 12.5. Only visible elements are indexed; always true, kept for forward compatibility. */
  visible: z.boolean(),
  /** True if the element's rect currently intersects the viewport. */
  inViewport: z.boolean(),
  /** Current value for input, textarea, select; null otherwise. Never populated for password fields. */
  value: z.string().max(ELEMENT_VALUE_MAX_CHARS).nullable(),
  /** Lowercase tagName, e.g. "button", "a", "input". */
  tag: LowercaseNonEmptySchema,
  /** input[type] lowercased, or null. */
  inputType: LowercaseNonEmptySchema.nullable(),
  /** True if input[type=password] (SPEC 8, R2.4). */
  isPassword: z.boolean(),
});

export type ElementIndexEntry = z.infer<typeof ElementIndexEntrySchema>;

// ---------------------------------------------------------------------------
// 5.2 ElementIndex
// ---------------------------------------------------------------------------

/** SPEC 5.2. Serialized form must stay under 24 KB for 120 elements. */
export const ElementIndexSchema = z.object({
  /** uuid, regenerated on every rebuild. Actions are validated against it (R2.3). */
  buildId: z.string().min(1),
  /** location.href at build time. Never sent to the model (SPEC 5.4). */
  url: z.string().min(1),
  /** document.title, truncated to 120 chars. */
  title: z.string().max(PAGE_TITLE_MAX_CHARS),
  builtAt: z.number(),
  viewportW: z.number(),
  viewportH: z.number(),
  /** Document scroll height, used for y normalization. */
  docH: z.number(),
  /** SPEC 12.2: capped at MAX_INDEX, document order. */
  entries: z.array(ElementIndexEntrySchema).max(MAX_INDEX),
  /** True if the element count exceeded MAX_INDEX and the list was capped. */
  truncated: z.boolean(),
});

export type ElementIndex = z.infer<typeof ElementIndexSchema>;

// ---------------------------------------------------------------------------
// 5.4.1 Region derivation, 5.4 PromptElement
// ---------------------------------------------------------------------------

/** SPEC 5.4: the coarse position the model sees instead of coordinates. */
export const REGIONS = ["top", "left", "center", "right", "bottom"] as const;

export const RegionSchema = z.enum(REGIONS);

export type Region = z.infer<typeof RegionSchema>;

/**
 * SPEC 5.4.1. The order of these tests is normative: the vertical bands are
 * checked before the horizontal ones, so a top-left element is "top".
 */
export function deriveRegion(x: number, y: number): Region {
  if (y < 0.15) return "top";
  if (y > 0.85) return "bottom";
  if (x < 0.3) return "left";
  if (x > 0.7) return "right";
  return "center";
}

/**
 * SPEC 5.4 — the only element data the model ever sees. The model never
 * receives href, src, CSS classes, page element ids, inner HTML, the page URL,
 * password-type elements, or any page text beyond names and values.
 */
export const PromptElementSchema = z.object({
  id: z.string().regex(ELEMENT_ID_PATTERN),
  role: LowercaseNonEmptySchema,
  /** Sanitized (SPEC 8.4), max 80 chars. */
  name: z.string().max(ELEMENT_NAME_MAX_CHARS),
  /** Sanitized, max 40 chars, omitted when null. */
  value: z.string().max(ELEMENT_VALUE_MAX_CHARS).optional(),
  region: RegionSchema,
});

export type PromptElement = z.infer<typeof PromptElementSchema>;

// ---------------------------------------------------------------------------
// 5.3 ResolveRequest
// ---------------------------------------------------------------------------

/** SPEC 5.3: one target, or a bounded sequence (SPEC 7.7). */
export const RESOLVE_MODES = ["single", "sequence"] as const;

export const ResolveModeSchema = z.enum(RESOLVE_MODES);

export type ResolveMode = z.infer<typeof ResolveModeSchema>;

/** SPEC 5.3, internal: service worker to Gemini client. */
export const ResolveRequestSchema = z.object({
  /** The user's words, normalized per SPEC 7.2.1, max 200 chars. */
  transcript: z.string().max(TRANSCRIPT_MAX_CHARS),
  index: z.array(PromptElementSchema),
  pageTitle: z.string().max(PAGE_TITLE_MAX_CHARS),
  mode: ResolveModeSchema,
  /** Present only when resolving a clarification reply; restricts the model to these ids. */
  candidateIds: z.array(z.string()).optional(),
});

export type ResolveRequest = z.infer<typeof ResolveRequestSchema>;

// ---------------------------------------------------------------------------
// 5.6 Verb, Action
// ---------------------------------------------------------------------------

/**
 * SPEC 5.6 / 5.5. The verb set is closed and contains no `navigate`:
 * navigation is only ever a side effect of clicking a real anchor that already
 * exists on the page, and the model cannot produce a URL (SPEC 8.3, R2.1).
 */
export const VERBS = [
  "click",
  "fill",
  "select",
  "check",
  "uncheck",
  "scrollTo",
  "focus",
] as const;

export const VerbSchema = z.enum(VERBS);

export type Verb = z.infer<typeof VerbSchema>;

/** SPEC 5.6 / 7.6.1 rule 6: `value` is present if and only if the verb is one of these. */
export const VALUE_REQUIRED_VERBS = ["fill", "select"] as const satisfies readonly Verb[];

function verbRequiresValue(verb: Verb): boolean {
  return (VALUE_REQUIRED_VERBS as readonly Verb[]).includes(verb);
}

/**
 * SPEC 5.6 (validated, internal). The `value` rule is enforced at runtime, not
 * only in the type: SPEC 7.6.1 rule 6 rejects an action whose `value` is
 * present for a verb that forbids it, or absent for one that requires it.
 */
export const ActionSchema = z
  .object({
    verb: VerbSchema,
    elementId: z.string(),
    /** Required for fill and select, forbidden otherwise. */
    value: z.string().optional(),
  })
  .superRefine((action, ctx) => {
    const requiresValue = verbRequiresValue(action.verb);
    if (requiresValue && action.value === undefined) {
      ctx.addIssue({
        code: "custom",
        path: ["value"],
        message: `value is required for verb "${action.verb}"`,
      });
    }
    if (!requiresValue && action.value !== undefined) {
      ctx.addIssue({
        code: "custom",
        path: ["value"],
        message: `value is forbidden for verb "${action.verb}"`,
      });
    }
  });

export type Action = z.infer<typeof ActionSchema>;

// ---------------------------------------------------------------------------
// 5.5 ResolverResponse
// ---------------------------------------------------------------------------

/**
 * SPEC 5.5 — the shape of a *parsed* Gemini response, mirroring the
 * `responseSchema` sent with the request.
 *
 * Deliberately looser than {@link ActionSchema}: `confidence` is not range
 * checked because SPEC 11.4 rule 5 requires an out-of-range value to be clamped
 * and penalised, not rejected, and `elementId` is not pattern checked because
 * SPEC 11.4 rule 3 treats an unknown id as a miss. Truncation of an
 * over-length `actions` array (SPEC 11.4 rule 4) happens before validation.
 */
export const ResolverResponseSchema = z.object({
  actions: z
    .array(
      z.object({
        verb: VerbSchema,
        elementId: z.string(),
        value: z.string().optional(),
      })
    )
    .max(MAX_ACTIONS),
  confidence: z.number(),
  ambiguousWith: z.array(z.string()).optional(),
  clarifyingQuestion: z.string().optional(),
});

export type ResolverResponse = z.infer<typeof ResolverResponseSchema>;

// ---------------------------------------------------------------------------
// 5.7 ExecuteRequest
// ---------------------------------------------------------------------------

/** SPEC 5.7: service worker to content script. */
export const ExecuteRequestSchema = z.object({
  /** The index build the actions were resolved against (R2.3). */
  buildId: z.string().min(1),
  /** 1..5 (SPEC 7.6.1 rule 9). */
  actions: z.array(ActionSchema).min(1).max(MAX_ACTIONS),
  stepDelayMs: z.number(),
  /** True when F-10 exists. */
  playTicks: z.boolean(),
});

export type ExecuteRequest = z.infer<typeof ExecuteRequestSchema>;

// ---------------------------------------------------------------------------
// 5.8 ExecuteResult, StepResult
// ---------------------------------------------------------------------------

/** SPEC 5.8. */
export const STEP_STATUSES = [
  "ok",
  "not_found",
  "not_actionable",
  "rejected",
  "error",
] as const;

export const StepStatusSchema = z.enum(STEP_STATUSES);

export type StepStatus = z.infer<typeof StepStatusSchema>;

/** SPEC 5.8. */
export const StepResultSchema = z.object({
  index: z.number().int().min(0),
  verb: VerbSchema,
  elementId: z.string(),
  /** Accessible name of the element actually acted on. */
  resolvedName: z.string().nullable(),
  status: StepStatusSchema,
  /** Short machine-readable reason, never raw page HTML. */
  detail: z.string().optional(),
});

export type StepResult = z.infer<typeof StepResultSchema>;

/** SPEC 5.8: content script to service worker. */
export const ExecuteResultSchema = z.object({
  ok: z.boolean(),
  /** Count of actions performed. */
  completed: z.number().int().min(0),
  results: z.array(StepResultSchema),
  failedAtIndex: z.number().int().min(0).nullable(),
});

export type ExecuteResult = z.infer<typeof ExecuteResultSchema>;

// ---------------------------------------------------------------------------
// 5.9 ClarificationState
// ---------------------------------------------------------------------------

/** SPEC 5.9. */
export const ClarificationStateSchema = z.object({
  /** What was spoken, max 90 chars. */
  question: z.string().max(CLARIFY_QUESTION_MAX_CHARS),
  /** 2..4 (SPEC 7.2.4). */
  candidateIds: z
    .array(z.string())
    .min(MIN_CLARIFY_CANDIDATES)
    .max(MAX_CLARIFY_CANDIDATES),
  /** The index build the candidates came from. */
  buildId: z.string().min(1),
  createdAt: z.number(),
  /** createdAt + 15000. */
  expiresAt: z.number(),
  /**
   * HD-14: the verb the original command named, carried across the question so
   * the reply executes what was asked. "Uncheck one of these two boxes" must
   * still be an uncheck after "the second one", not the default click, whose
   * direction depends on the state the box happens to be in. Absent when the
   * command named no verb.
   */
  verb: VerbSchema.optional(),
});

export type ClarificationState = z.infer<typeof ClarificationStateSchema>;

// ---------------------------------------------------------------------------
// 5.10 AudioEvent
// ---------------------------------------------------------------------------

/** SPEC 5.10: a scan entry carries its id so the highlight can be synchronized (SPEC 9.7). */
const ScanEntrySchema = z.object({
  id: z.string(),
  x: NormalizedCoordSchema,
  y: NormalizedCoordSchema,
  role: LowercaseNonEmptySchema,
});

/** SPEC 5.10: a mutation point has no id; it is ambient, not addressable (SPEC 9.8). */
const AudioPointSchema = z.object({
  x: NormalizedCoordSchema,
  y: NormalizedCoordSchema,
  role: LowercaseNonEmptySchema,
});

/** SPEC 5.10: discriminated on `kind`. */
export const AudioEventSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("listenStart") }),
  z.object({ kind: z.literal("listenEnd") }),
  z.object({ kind: z.literal("scan"), entries: z.array(ScanEntrySchema) }),
  z.object({
    kind: z.literal("tick"),
    x: NormalizedCoordSchema,
    y: NormalizedCoordSchema,
    role: LowercaseNonEmptySchema,
  }),
  z.object({ kind: z.literal("mutation"), points: z.array(AudioPointSchema) }),
  z.object({ kind: z.literal("error") }),
]);

export type AudioEvent = z.infer<typeof AudioEventSchema>;

// ---------------------------------------------------------------------------
// 5.11 MutationEvent
// ---------------------------------------------------------------------------

/** SPEC 5.11. */
export const MutationEventSchema = z.object({
  /** The new build id after the rebuild. */
  buildId: z.string().min(1),
  /** Entries present in the new index and absent from the previous one. */
  addedIds: z.array(z.string()),
  removedIds: z.array(z.string()),
  at: z.number(),
});

export type MutationEvent = z.infer<typeof MutationEventSchema>;

// ---------------------------------------------------------------------------
// 5.12 SummaryRecord
// ---------------------------------------------------------------------------

/** SPEC 5.12: sha256 of location.href, hex, first 16 chars. The URL itself is never stored. */
export const URL_HASH_PATTERN = /^[0-9a-f]{16}$/;

/** SPEC 5.12 (stored). */
export const SummaryRecordSchema = z.object({
  urlHash: z.string().regex(URL_HASH_PATTERN),
  /** The summary, max 1200 chars. */
  text: z.string().max(SUMMARY_MAX_CHARS),
  createdAt: z.number(),
  /** Model identifier used, or "cache-seed". */
  model: z.string().min(1),
});

export type SummaryRecord = z.infer<typeof SummaryRecordSchema>;

// ---------------------------------------------------------------------------
// 5.13 Settings
// ---------------------------------------------------------------------------

/** SPEC 5.13: spoken verbosity; also selects the TTS rate. */
export const VERBOSITIES = ["fast", "verbose"] as const;

export const VerbositySchema = z.enum(VERBOSITIES);

export type Verbosity = z.infer<typeof VerbositySchema>;

/** SPEC 5.13 (stored). */
export const SettingsSchema = z.object({
  /** Service worker only. Never reaches the content script or offscreen bundles (R2.5). */
  geminiApiKey: z.string().nullable(),
  /** Default from ENVIRONMENT.md, user-overridable. */
  geminiModel: z.string().min(1),
  /** Default "fast". */
  verbosity: VerbositySchema,
  /** Resolved at startup (SPEC 10.6.2). */
  ttsVoiceName: z.string().nullable(),
  /** fast: 1.6, verbose: 1.0. */
  ttsRate: z.number(),
  /** Default "Space". */
  holdKey: z.string().min(1),
  /** Default "KeyM" with Alt. */
  scanKey: z.string().min(1),
  /** Default false. */
  telemetryEnabled: z.boolean(),
  /** Default true. */
  audioEnabled: z.boolean(),
  /** HD-A06 / HD-07: Use local chrome.tts (true) or ElevenLabs cloud API (false). Default true. */
  useLocalTts: z.boolean().default(true),
  /** ElevenLabs API key for cloud TTS. Read from chrome.storage.local. */
  elevenLabsApiKey: z.string().nullable().default(null),
  /**
   * HD-12: mutation sonification (F-17). **Default false** — the human listened
   * to it and did not want the page making noise as it changes. The engine and
   * its tests stay; nothing starts unless this is turned on.
   */
  mutationAudio: z.boolean().default(false),
  /**
   * HD-12: pan spoken answers to where the thing they are about actually is on
   * the page, so "Clicked Search flights" arrives from the left if the button
   * is on the left. Default true. Only has an effect on the ElevenLabs path —
   * `chrome.tts` output cannot be routed into a Web Audio graph (SPEC 9.1).
   */
  spatialLinks: z.boolean().default(true),
  /**
   * HD-13 (F-22): GPTZero key for synthetic-text detection. Service worker only,
   * same boundary as `geminiApiKey` (R2.5). Null disables detection outright.
   */
  gptZeroApiKey: z.string().nullable().default(null),
  /**
   * HD-13 (F-22): warn before reading a page that scores as A.I. generated.
   * Default true. Turning it off stops page text reaching GPTZero at all.
   */
  aiDetection: z.boolean().default(true),
});

export type Settings = z.infer<typeof SettingsSchema>;

// ---------------------------------------------------------------------------
// 5.14 TelemetryRecord
// ---------------------------------------------------------------------------

/** SPEC 5.14: which resolution tier produced the outcome. */
export const TELEMETRY_TIERS = ["local", "model", "clarify"] as const;

export const TelemetryTierSchema = z.enum(TELEMETRY_TIERS);

export type TelemetryTier = z.infer<typeof TelemetryTierSchema>;

/** SPEC 5.14. */
export const TELEMETRY_OUTCOMES = ["executed", "clarified", "failed"] as const;

export const TelemetryOutcomeSchema = z.enum(TELEMETRY_OUTCOMES);

export type TelemetryOutcome = z.infer<typeof TelemetryOutcomeSchema>;

/**
 * SPEC 5.14 (F-18 only). A record must never contain the page URL, page
 * content, an element name other than the single resolved name, or any part of
 * the API key.
 */
export const TelemetryRecordSchema = z.object({
  ts: z.number(),
  /** Max 120 chars. */
  transcript: z.string().max(TELEMETRY_TRANSCRIPT_MAX_CHARS),
  tier: TelemetryTierSchema,
  confidence: z.number(),
  /** Key release to first action executed. */
  latencyMs: z.number(),
  actionCount: z.number().int().min(0),
  resolvedName: z.string().nullable(),
  outcome: TelemetryOutcomeSchema,
});

export type TelemetryRecord = z.infer<typeof TelemetryRecordSchema>;

// ---------------------------------------------------------------------------
// 5.15 Message envelope
// ---------------------------------------------------------------------------

/** SPEC 5.15: constant, always present, so unrelated listeners can cheaply ignore our messages. */
export const ENVELOPE_NS = "echo";

/** SPEC 5.15. */
export const ENVELOPE_TARGETS = ["sw", "content", "offscreen"] as const;

export const EnvelopeTargetSchema = z.enum(ENVELOPE_TARGETS);

export type EnvelopeTarget = z.infer<typeof EnvelopeTargetSchema>;

/**
 * SPEC 5.15. The TS interface, for the many places that hold an envelope
 * without needing a payload schema for it.
 */
export interface Envelope<T = unknown> {
  ns: typeof ENVELOPE_NS;
  target: EnvelopeTarget;
  /** See SPEC 5.16 / {@link MESSAGE_TYPES}. */
  type: string;
  /** uuid, echoed in the response. */
  reqId: string;
  payload: T;
}

/**
 * SPEC 5.15, runtime form. Zod schemas are not generic the way the interface
 * is, so the envelope is built per payload schema:
 * `envelopeSchema(ExecuteRequestSchema)`.
 */
export function envelopeSchema<T extends z.ZodType>(payload: T) {
  return z.object({
    ns: z.literal(ENVELOPE_NS),
    target: EnvelopeTargetSchema,
    type: z.string().min(1),
    reqId: z.string().min(1),
    payload,
  });
}

/** SPEC 5.15, the unvalidated envelope with an opaque payload. */
export const AnyEnvelopeSchema = envelopeSchema(z.unknown());

/**
 * SPEC 5.15 `[REQUIREMENT]`: every listener returns early if `msg?.ns !== "echo"`
 * or `msg.target` does not match its own role.
 *
 * `msg` arrives from a `chrome.runtime` listener as genuinely unknown data — it
 * may be null, a string, or a message from an unrelated extension — so nothing
 * about its shape is assumed before it is checked. The payload is *not*
 * validated here; the listener validates it with the schema for its own message
 * type.
 */
export function isEnvelopeFor<T = unknown>(
  msg: unknown,
  target: EnvelopeTarget
): msg is Envelope<T> {
  if (typeof msg !== "object" || msg === null) return false;
  const candidate = msg as Record<string, unknown>;
  return (
    candidate.ns === ENVELOPE_NS &&
    candidate.target === target &&
    typeof candidate.type === "string" &&
    typeof candidate.reqId === "string"
  );
}

// ---------------------------------------------------------------------------
// 5.16 Message type catalogue
// ---------------------------------------------------------------------------

/**
 * SPEC 5.16, the `type` column. One source of truth so no call site hand-types
 * a message string. Payload and response shapes for each are the schemas above;
 * each message's handler validates its own payload (SPEC 5.16 table).
 */
export const MESSAGE_TYPES = [
  "key.down",
  "key.up",
  "stt.start",
  "stt.stop",
  "stt.result",
  "stt.error",
  "index.get",
  "index.changed",
  "exec.run",
  "audio.play",
  "ui.highlight",
  "ui.blackout",
  "page.text",
  "scan.request",
  "state.get",
] as const;

export type MessageType = (typeof MESSAGE_TYPES)[number];

// ---------------------------------------------------------------------------
// 5.15 AuthenticityVerdict (F-22, HD-13)
// ---------------------------------------------------------------------------

/**
 * What the detector concluded about a page's text.
 *
 *   high  — most of it scores as machine written
 *   mixed — some of it does
 *   clean — it does not
 *
 * There is no "unknown" band. A detector that did not run, timed out, has no
 * key, or returned something unreadable produces `null`, not a verdict, and the
 * answer goes out exactly as it would have before (SPEC 19.3: no new network
 * dependency on the demo path).
 */
export const AUTHENTICITY_LEVELS = ["clean", "mixed", "high"] as const;

export const AuthenticityLevelSchema = z.enum(AUTHENTICITY_LEVELS);

export type AuthenticityLevel = z.infer<typeof AuthenticityLevelSchema>;

/**
 * One paragraph that scored above the flag threshold. HD-14: a page is not one
 * number. A mostly human article with a single machine-written section is the
 * case that matters most, and a whole-document probability is exactly the
 * statistic that hides it.
 */
export const FlaggedSectionSchema = z.object({
  /**
   * The paragraph's opening words, sanitized and capped, so the model can name
   * which part of the page it means. Null when the response carried paragraph
   * scores but no sentence text to rebuild them from.
   */
  excerpt: z.string().nullable(),
  /** P(machine written) for this paragraph, 0..1. */
  aiProbability: z.number().min(0).max(1),
  /** Length of the paragraph in characters. */
  chars: z.number().int().min(0),
  /** 1-based position among the eligible paragraphs, for "the third section". */
  position: z.number().int().min(1),
});

export type FlaggedSection = z.infer<typeof FlaggedSectionSchema>;

export const AuthenticityVerdictSchema = z.object({
  level: AuthenticityLevelSchema,
  /** P(machine written) for the whole document, 0..1. */
  aiProbability: z.number().min(0).max(1),
  /** GPTZero's own document_classification, when it sent one. Diagnostic only. */
  classification: z.string().nullable(),
  /** Characters actually classified, which is the sample, not the page. */
  sampledChars: z.number().int().min(0),
  /** Paragraphs at or above the flag threshold and long enough to judge (HD-14). */
  flagged: z.array(FlaggedSectionSchema).default([]),
  /** Paragraphs that were long enough to be judged at all. */
  paragraphsConsidered: z.number().int().min(0).default(0),
  /** Characters inside the flagged paragraphs, for "how much of the page". */
  flaggedChars: z.number().int().min(0).default(0),
});

export type AuthenticityVerdict = z.infer<typeof AuthenticityVerdictSchema>;
